services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/database/database.sqlite
    volumes:
      - ./:/var/www
